// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eurojbezpyvkvejtzzxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cm9qYmV6cHl2a3ZlanR6enhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjQ3MDMsImV4cCI6MjA3MjQwMDcwM30.33t8r5l5o0DwTbisdw15cr2W5opXDmbe4Wwy_oFWQ1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});